apiVersion: v1
kind: Service
metadata:
  name: hashresponse-svc
spec:
  type: ClusterIP
  selector:
    app: hashresponse
  ports: # will let TCP traffic from port 2345 to port 3000
    - port: 2345
      protocol: TCP
      targetPort: 3000
