apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dwk-material-ingress
spec:
  rules:
    - http:
        paths:
          - path: /response
            pathType: Prefix
            backend:
              service:
                name: response-svc
                port:
                  number: 1234
          - path: /finder
            pathType: Prefix
            backend:
              service:
                name: finder-svc
                port:
                  number: 2345
